### ISSUE TITLE
Problem with Astro theme catalogue description

### ISSUE THREAD

**Issue by sarah11918** [CedricLphn/astrojs-theme-jane#1]
Hi there! I just approved your theme for the Astro Theme catalogue, but I will need you to update your description. As you can see, you can't use HTML in the text field where you provide your description.

I didn't want to reject your theme just for this alone! But you will need to update this or we will have to remove it:

![image](https://github.com/user-attachments/assets/b1068a4e-e39c-42fe-baa7-7e488ca913c6)
 
Please log in to the theme portal and remove the HTML from the description at your earliest convenience, and thank you for submitting a theme! :partying_face:

**Comment by CedricLphn** [comment]
Tkank you very much. I'd use makedown for write the description but I did'nt know why it's formatted in HTML
